/**
 * MediGuide AI — SummaryCard
 * Formatted doctor-ready symptom summary card.
 * Supports sharing via Web Share API and print.
 */

import { FiFileText, FiShare2, FiPrinter, FiCopy, FiCheck } from 'react-icons/fi'
import { useState } from 'react'
import toast from 'react-hot-toast'

export default function SummaryCard({ summary, urgency, language = 'en' }) {
  const [copied, setCopied] = useState(false)

  if (!summary) return null

  const summaryText = typeof summary === 'string' ? summary : JSON.stringify(summary, null, 2)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
      toast.success(language === 'hi' ? 'कॉपी हो गया' : 'Copied to clipboard')
    } catch {
      toast.error('Copy failed')
    }
  }

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'MediGuide AI — Doctor Summary',
          text: summaryText,
        })
      } catch (err) {
        if (err.name !== 'AbortError') console.error(err)
      }
    } else {
      handleCopy()
    }
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>MediGuide AI — Doctor Summary</title>
          <style>
            body { font-family: 'Inter', 'Segoe UI', sans-serif; padding: 40px; max-width: 600px; margin: 0 auto; }
            h1 { font-size: 18px; color: #1a6ff5; margin-bottom: 4px; }
            h2 { font-size: 12px; color: #64748b; font-weight: normal; margin-bottom: 24px; }
            pre { white-space: pre-wrap; font-family: inherit; font-size: 13px; line-height: 1.8; color: #1e293b; }
            .footer { margin-top: 30px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <h1>🏥 MediGuide AI — Doctor Summary</h1>
          <h2>Generated: ${new Date().toLocaleString()}</h2>
          <pre>${summaryText}</pre>
          <div class="footer">This summary was generated by MediGuide AI to assist medical professionals. It is not a diagnosis.</div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  const urgencyBadge = {
    emergency: { bg: 'bg-red-500/20', text: 'text-red-400', label: '🔴 Emergency' },
    moderate:  { bg: 'bg-yellow-500/20', text: 'text-yellow-400', label: '🟡 Moderate' },
    mild:      { bg: 'bg-green-500/20', text: 'text-green-400', label: '🟢 Mild' },
  }

  const badge = urgencyBadge[urgency]

  return (
    <div className="glass-card overflow-hidden animate-slide-up">
      {/* Header */}
      <div className="px-4 py-3 bg-primary-600/10 border-b border-surface-700/30 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FiFileText className="w-4 h-4 text-primary-400" />
          <span className="text-sm font-bold text-white">
            {language === 'hi' ? 'डॉक्टर रिपोर्ट' : 'Doctor Summary'}
          </span>
        </div>
        {badge && (
          <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${badge.bg} ${badge.text}`}>
            {badge.label}
          </span>
        )}
      </div>

      {/* Summary Content */}
      <div className="px-4 py-3">
        <pre className="text-xs text-surface-300 whitespace-pre-wrap font-sans leading-relaxed">
          {summaryText}
        </pre>
      </div>

      {/* Actions */}
      <div className="px-4 py-2.5 border-t border-surface-700/30 flex items-center gap-2">
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface-800/60 text-surface-300 hover:text-white text-[11px] transition-all hover:bg-surface-700"
        >
          {copied ? <FiCheck className="w-3 h-3 text-green-400" /> : <FiCopy className="w-3 h-3" />}
          {language === 'hi' ? 'कॉपी' : 'Copy'}
        </button>
        <button
          onClick={handleShare}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface-800/60 text-surface-300 hover:text-white text-[11px] transition-all hover:bg-surface-700"
        >
          <FiShare2 className="w-3 h-3" />
          {language === 'hi' ? 'शेयर' : 'Share'}
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surface-800/60 text-surface-300 hover:text-white text-[11px] transition-all hover:bg-surface-700"
        >
          <FiPrinter className="w-3 h-3" />
          {language === 'hi' ? 'प्रिंट' : 'Print'}
        </button>
      </div>
    </div>
  )
}
