/**
 * MediGuide AI — Health Card PDF Generator
 * Generates a professional, printable Health Card PDF from triage results.
 *
 * Approach: Renders a styled HTML card off-screen → html2canvas captures it
 * as a high-res image → jsPDF wraps it into a downloadable A4 PDF.
 * This ensures full Hindi/Marathi/Devanagari support since the browser
 * handles all font rendering natively.
 */

import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

// ── Urgency Config ───────────────────────────────────────────

const URGENCY_STYLES = {
  mild: {
    bg: '#dcfce7', border: '#16a34a', text: '#166534',
    emoji: '🟢', label: { hi: 'हल्का', mr: 'सौम्य', en: 'Mild' },
    advice: {
      hi: 'आपकी स्थिति गंभीर नहीं है। 1-3 दिन में डॉक्टर से मिलें।',
      mr: 'तुमची स्थिती गंभीर नाही. 1-3 दिवसात डॉक्टरांना भेटा.',
      en: 'Your condition is not serious. Visit a doctor within 1-3 days.',
    },
  },
  moderate: {
    bg: '#fef9c3', border: '#ca8a04', text: '#854d0e',
    emoji: '🟡', label: { hi: 'मध्यम', mr: 'मध्यम', en: 'Moderate' },
    advice: {
      hi: 'कृपया 24 घंटे के भीतर डॉक्टर से मिलें।',
      mr: 'कृपया 24 तासांच्या आत डॉक्टरांना भेटा.',
      en: 'Please visit a doctor within 24 hours.',
    },
  },
  emergency: {
    bg: '#fee2e2', border: '#dc2626', text: '#991b1b',
    emoji: '🔴', label: { hi: 'आपातकालीन', mr: 'आणीबाणी', en: 'Emergency' },
    advice: {
      hi: 'तुरंत अस्पताल जाएं या 108 पर एम्बुलेंस बुलाएं!',
      mr: 'ताबडतोब रुग्णालयात जा किंवा 108 वर कॉल करा!',
      en: 'Go to the hospital immediately or call 108 ambulance!',
    },
  },
}

const LABELS = {
  title:       { hi: 'स्वास्थ्य कार्ड', mr: 'आरोग्य कार्ड', en: 'Health Card' },
  patient:     { hi: 'रोगी की जानकारी', mr: 'रुग्णाची माहिती', en: 'Patient Information' },
  name:        { hi: 'नाम', mr: 'नाव', en: 'Name' },
  age:         { hi: 'उम्र', mr: 'वय', en: 'Age' },
  gender:      { hi: 'लिंग', mr: 'लिंग', en: 'Gender' },
  date:        { hi: 'दिनांक', mr: 'दिनांक', en: 'Date' },
  urgency:     { hi: 'तात्कालिकता', mr: 'आपत्कालीन', en: 'Urgency Level' },
  complaint:   { hi: 'मुख्य समस्या', mr: 'मुख्य तक्रार', en: 'Chief Complaint' },
  duration:    { hi: 'कब से', mr: 'कालावधी', en: 'Duration' },
  severity:    { hi: 'गंभीरता', mr: 'तीव्रता', en: 'Severity' },
  symptoms:    { hi: 'संबंधित लक्षण', mr: 'संबंधित लक्षणे', en: 'Associated Symptoms' },
  history:     { hi: 'चिकित्सा इतिहास', mr: 'वैद्यकीय इतिहास', en: 'Medical History' },
  assessment:  { hi: 'AI मूल्यांकन', mr: 'AI मूल्यांकन', en: 'AI Assessment' },
  specialty:   { hi: 'सुझाई गई विशेषता', mr: 'सुचवलेले विशेष', en: 'Recommended Specialty' },
  advice:      { hi: 'सलाह', mr: 'सल्ला', en: 'Advice' },
  conversation: { hi: 'बातचीत सारांश', mr: 'संभाषण सारांश', en: 'Conversation Summary' },
  disclaimer:  {
    hi: '⚠️ यह AI-सहायित ट्राइएज रिपोर्ट है, चिकित्सा निदान नहीं। कृपया इसे अपने डॉक्टर को दिखाएं।',
    mr: '⚠️ हे AI-सहाय्यित ट्रायएज अहवाल आहे, वैद्यकीय निदान नाही. कृपया डॉक्टरांना दाखवा.',
    en: '⚠️ This is an AI-assisted triage report, not a medical diagnosis. Please show this to your doctor.',
  },
  clinicalDetails: { hi: 'नैदानिक विवरण', mr: 'क्लिनिकल तपशील', en: 'Clinical Details' },
  symptomImage: { hi: 'लक्षण छवि', mr: 'लक्षण प्रतिमा', en: 'Symptom Image' },
  subtitle: { hi: 'AI-संचालित स्वास्थ्य ट्राइएज रिपोर्ट', mr: 'AI-संचालित आरोग्य ट्रायएज अहवाल', en: 'AI-Powered Healthcare Triage Report' },
  generatedBy: { hi: 'MediGuide AI द्वारा निर्मित', mr: 'MediGuide AI द्वारे तयार', en: 'Generated by MediGuide AI' },
}

// ── Helpers ───────────────────────────────────────────────────

function L(key, lang) {
  return LABELS[key]?.[lang] || LABELS[key]?.en || key
}

function extractUserSymptoms(messages) {
  return messages
    .filter(m => m.role === 'user')
    .map(m => m.content)
}

/** Extract the user-uploaded image from the message history */
function extractUserImage(messages) {
  for (const msg of messages) {
    if (msg.image) return msg.image
  }
  return null
}

/** Translate gender for display in the user's language */
function translateGender(gender, lang) {
  const genderLabels = {
    male:   { hi: 'पुरुष',  mr: 'पुरुष',  en: 'Male' },
    female: { hi: 'महिला',  mr: 'स्त्री', en: 'Female' },
    other:  { hi: 'अन्य',   mr: 'इतर',    en: 'Other' },
  }
  const g = (gender || '').toLowerCase()
  return genderLabels[g]?.[lang] || genderLabels[g]?.en || gender || '—'
}

function formatDateTime(lang) {
  const now = new Date()
  try {
    const locale = lang === 'hi' ? 'hi-IN' : lang === 'mr' ? 'mr-IN' : 'en-IN'
    return now.toLocaleString(locale, {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  } catch {
    return now.toLocaleString('en-IN')
  }
}

/** Build an HTML row for a field (label: value) */
function fieldRow(label, value) {
  if (!value || value === '—') return ''
  return `
    <tr>
      <td style="padding: 6px 12px; font-size: 11px; font-weight: 600; color: #64748b; white-space: nowrap; vertical-align: top; border-bottom: 1px solid #f1f5f9;">${label}</td>
      <td style="padding: 6px 12px; font-size: 12px; color: #1e293b; border-bottom: 1px solid #f1f5f9;">${value}</td>
    </tr>
  `
}

// ── Build HTML Card ──────────────────────────────────────────

function buildCardHTML({
  patientName, age, gender, language, urgency, urgencyData, messages, summary,
}) {
  const lang = language || 'en'
  const urg = URGENCY_STYLES[urgency] || URGENCY_STYLES.mild
  const symptoms = extractUserSymptoms(messages)
  const userImage = extractUserImage(messages)
  const specialty = urgencyData?.recommend_specialty || summary?.recommend_specialty || '—'
  const dateStr = formatDateTime(lang)

  // Extract summary fields
  const chiefComplaint = summary?.chief_complaint || symptoms[0] || '—'
  const duration = summary?.duration || '—'
  const severity = summary?.severity || '—'
  const associatedSymptoms = summary?.associated_symptoms?.join(', ') || '—'
  const relevantHistory = summary?.relevant_history || 'None reported'
  // Sanitize full_summary: strip any JSON artifacts that may have leaked
  let fullSummary = summary?.full_summary || ''
  fullSummary = fullSummary
    .replace(/```(?:json)?\s*\{[\s\S]*?\}\s*```/g, '')  // remove ```json...``` blocks
    .replace(/\{\s*"type"\s*:\s*"result"[\s\S]*?\}/g, '') // remove raw JSON objects
    .replace(/```[\s\S]*?```/g, '')                       // remove any code blocks
    .replace(/\n{3,}/g, '\n\n')                           // collapse whitespace
    .trim()

  return `
    <div id="mediguide-health-card" style="
      width: 620px;
      font-family: 'Inter', 'Noto Sans Devanagari', 'Segoe UI', system-ui, sans-serif;
      background: #ffffff;
      color: #1e293b;
      padding: 0;
    ">
      <!-- Header -->
      <div style="
        background: linear-gradient(135deg, #1a6ff5, #1259e1, #7c3aed);
        color: white;
        padding: 24px 28px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      ">
        <div>
          <div style="font-size: 22px; font-weight: 800; letter-spacing: -0.5px;">
            🏥 MediGuide ${L('title', lang)}
          </div>
          <div style="font-size: 11px; opacity: 0.75; margin-top: 4px;">
            ${L('subtitle', lang)}
          </div>
        </div>
        <div style="text-align: right; font-size: 10px; opacity: 0.7;">
          ${dateStr}
        </div>
      </div>

      <!-- Body -->
      <div style="padding: 20px 28px;">

        <!-- Patient Info + Urgency Row -->
        <div style="display: flex; gap: 16px; margin-bottom: 20px;">
          <!-- Patient Card -->
          <div style="
            flex: 1;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            padding: 14px 16px;
          ">
            <div style="font-size: 10px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 10px;">
              ${L('patient', lang)}
            </div>
            <div style="font-size: 16px; font-weight: 700; color: #1e293b; margin-bottom: 6px;">
              ${patientName || 'Patient'}
            </div>
            <div style="display: flex; gap: 20px; font-size: 11px; color: #64748b;">
              <span>${L('age', lang)}: <strong>${age || '—'}</strong></span>
              <span>${L('gender', lang)}: <strong>${translateGender(gender, lang)}</strong></span>
            </div>
          </div>

          <!-- Urgency Badge -->
          <div style="
            width: 160px;
            background: ${urg.bg};
            border: 2px solid ${urg.border};
            border-radius: 10px;
            padding: 14px 16px;
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
          ">
            <div style="font-size: 28px; margin-bottom: 4px;">${urg.emoji}</div>
            <div style="font-size: 10px; font-weight: 700; color: ${urg.text}; text-transform: uppercase; letter-spacing: 1px;">
              ${L('urgency', lang)}
            </div>
            <div style="font-size: 16px; font-weight: 800; color: ${urg.text};">
              ${urg.label[lang] || urg.label.en}
            </div>
          </div>
        </div>

        <!-- Clinical Details Table -->
        <div style="margin-bottom: 20px;">
          <div style="font-size: 11px; font-weight: 700; color: #1a6ff5; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 2px solid #1a6ff5;">
            ${L('clinicalDetails', lang)}
          </div>
          <table style="width: 100%; border-collapse: collapse;">
            ${fieldRow(L('complaint', lang), chiefComplaint)}
            ${fieldRow(L('duration', lang), duration)}
            ${fieldRow(L('severity', lang), severity)}
            ${fieldRow(L('symptoms', lang), associatedSymptoms)}
            ${fieldRow(L('history', lang), relevantHistory)}
            ${fieldRow(L('specialty', lang), `<span style="text-transform: capitalize; font-weight: 600; color: #1a6ff5;">${specialty}</span>`)}
          </table>
        </div>

        ${userImage ? `
        <!-- Uploaded Image -->
        <div style="margin-bottom: 20px;">
          <div style="font-size: 11px; font-weight: 700; color: #1a6ff5; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 2px solid #1a6ff5;">
            ${L('symptomImage', lang)}
          </div>
          <div style="border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; display: inline-block;">
            <img src="${userImage}" style="max-width: 200px; max-height: 150px; object-fit: contain; display: block;" />
          </div>
        </div>
        ` : ''}

        <!-- AI Assessment -->
        ${fullSummary ? `
        <div style="margin-bottom: 20px;">
          <div style="font-size: 11px; font-weight: 700; color: #1a6ff5; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 2px solid #1a6ff5;">
            ${L('assessment', lang)}
          </div>
          <div style="
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 12px 14px;
            font-size: 12px;
            line-height: 1.7;
            color: #334155;
          ">
            ${fullSummary}
          </div>
        </div>
        ` : ''}

        <!-- Advice -->
        <div style="
          background: ${urg.bg};
          border: 1px solid ${urg.border};
          border-radius: 8px;
          padding: 12px 14px;
          margin-bottom: 16px;
          font-size: 12px;
          font-weight: 600;
          color: ${urg.text};
          display: flex;
          align-items: center;
          gap: 8px;
        ">
          <span style="font-size: 16px;">💡</span>
          ${urg.advice[lang] || urg.advice.en}
        </div>

        <!-- Conversation Log -->
        <div style="margin-bottom: 16px;">
          <div style="font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px;">
            ${L('conversation', lang)}
          </div>
          <div style="font-size: 10px; color: #94a3b8; line-height: 1.6; max-height: 120px; overflow: hidden;">
            ${symptoms.map((s, i) => `<div style="margin-bottom: 2px;"><strong>•</strong> ${s}</div>`).join('')}
          </div>
        </div>

        <!-- Disclaimer -->
        <div style="
          background: #fffbeb;
          border: 1px solid #fcd34d;
          border-radius: 8px;
          padding: 10px 14px;
          font-size: 10px;
          line-height: 1.5;
          color: #92400e;
        ">
          ${L('disclaimer', lang)}
        </div>
      </div>

      <!-- Footer -->
      <div style="
        background: #f1f5f9;
        border-top: 1px solid #e2e8f0;
        padding: 10px 28px;
        display: flex;
        justify-content: space-between;
        font-size: 9px;
        color: #94a3b8;
      ">
        <span>${L('generatedBy', lang)}</span>
        <span>${dateStr}</span>
      </div>
    </div>
  `
}

// ── Main Export ───────────────────────────────────────────────

/**
 * Generate and download a PDF Health Card.
 *
 * @param {Object} params
 * @param {string} params.patientName
 * @param {string} params.age
 * @param {string} params.gender
 * @param {string} params.language      - "hi" | "mr" | "en"
 * @param {string} params.urgency       - "mild" | "moderate" | "emergency"
 * @param {Object} params.urgencyData   - Full triage response data
 * @param {Array}  params.messages      - Chat messages array
 * @param {Object} params.summary       - Doctor summary object
 */
export async function generateHealthCard(params) {
  // 1. Create off-screen container
  const container = document.createElement('div')
  container.style.cssText =
    'position:fixed; top:-9999px; left:-9999px; z-index:-1; pointer-events:none;'
  container.innerHTML = buildCardHTML(params)
  document.body.appendChild(container)

  const cardEl = container.querySelector('#mediguide-health-card')

  try {
    // 2. Wait for fonts to load
    await document.fonts.ready

    // 3. Render to canvas at 2x resolution for crisp output
    const canvas = await html2canvas(cardEl, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
    })

    // 4. Convert to PDF (A4 portrait: 210 × 297 mm)
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = pdf.internal.pageSize.getHeight()

    // Fit card image to A4 with margins
    const margin = 8
    const imgWidth = pdfWidth - margin * 2
    const imgHeight = (canvas.height / canvas.width) * imgWidth

    // If card is taller than page, scale down to fit
    const usedHeight = Math.min(imgHeight, pdfHeight - margin * 2)
    const usedWidth = (usedHeight / imgHeight) * imgWidth

    const x = (pdfWidth - usedWidth) / 2
    const y = margin

    const imgData = canvas.toDataURL('image/png')
    pdf.addImage(imgData, 'PNG', x, y, usedWidth, usedHeight)

    // 5. Download
    const timestamp = new Date().toISOString().slice(0, 10)
    pdf.save(`MediGuide_HealthCard_${timestamp}.pdf`)

    return true
  } finally {
    // Cleanup
    document.body.removeChild(container)
  }
}

export default generateHealthCard
